[tool.poetry]
name = "code-challenges"
version = "1.0.0"
description = "Solutions for coding challenges"
authors = ["waan <admin@waan.email>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
argcomplete = "3.2.2"
asttokens = "2.4.1"
click = "8.1.7"
comm = "0.2.1"
debugpy = "1.8.1"
decorator = "5.1.1"
exceptiongroup = "1.2.0"
executing = "2.0.1"
ipykernel = "6.29.2"
ipython = "8.21.0"
jedi = "0.19.1"
jupyter-client = "8.6.0"
jupyter-core = "5.7.1"
matplotlib-inline = "0.1.6"
nest-asyncio = "1.6.0"
packaging = "23.2"
parso = "0.8.3"
pexpect = "4.9.0"
pipx = "1.4.3"
platformdirs = "4.2.0"
prompt-toolkit = "3.0.43"
psutil = "5.9.8"
ptyprocess = "0.7.0"
pure-eval = "0.2.2"
pygments = "2.17.2"
python-dateutil = "2.8.2"
pyzmq = "25.1.2"
six = "1.16.0"
stack-data = "0.6.3"
tomli = "2.0.1"
tornado = "6.4"
traitlets = "5.14.1"
userpath = "1.9.1"
wcwidth = "0.2.13"


[tool.poetry.group.dev.dependencies]
argcomplete = "3.2.2"
asttokens = "2.4.1"
click = "8.1.7"
comm = "0.2.1"
coverage = "7.4.2"
debugpy = "1.8.1"
decorator = "5.1.1"
exceptiongroup = "1.2.0"
executing = "2.0.1"
iniconfig = "2.0.0"
ipykernel = "6.29.2"
ipython = "8.21.0"
jedi = "0.19.1"
jupyter-client = "8.6.0"
jupyter-core = "5.7.1"
matplotlib-inline = "0.1.6"
nest-asyncio = "1.6.0"
packaging = "23.2"
parso = "0.8.3"
pexpect = "4.9.0"
pipx = "1.4.3"
platformdirs = "4.2.0"
pluggy = "1.4.0"
prompt-toolkit = "3.0.43"
psutil = "5.9.8"
ptyprocess = "0.7.0"
pure-eval = "0.2.2"
pygments = "2.17.2"
pytest = "8.0.1"
pytest-cov = "4.1.0"
python-dateutil = "2.8.2"
pyzmq = "25.1.2"
six = "1.16.0"
stack-data = "0.6.3"
tomli = "2.0.1"
tornado = "6.4"
traitlets = "5.14.1"
userpath = "1.9.1"
wcwidth = "0.2.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
